services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./volumes/ollama:/root/.ollama
    tty: true
    stdin_open: true
    healthcheck:
      test: [ "CMD", "ollama", "list" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    restart: always
    networks:
      - ollama-network

  openwebui:
    image: ghcr.io/open-webui/open-webui
    container_name: openwebui
    ports:
      - "8081:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./volumes/openwebui_data:/app/backend/data
    restart: always
    networks:
      - ollama-network
    depends_on:
      ollama:
        condition: service_healthy

  open_notebook:
    image: lfnovo/open_notebook:v1-latest-single
    ports:
      - "8502:8502"
      - "5055:5055"
      - "8000:8000"
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
      # API Server connection
      - API_URL=http://localhost:5055
      # Database connection (required)
      - SURREAL_URL=ws://localhost:8000/rpc
      - SURREAL_USER=root
      - SURREAL_PASSWORD=root
      - SURREAL_NAMESPACE=open_notebook
      - SURREAL_DATABASE=production
    volumes:
      - ./volumes/notebook_data:/app/data
      - ./volumes/surreal_single_data:/mydata
    networks:
      - ollama-network
    depends_on:
      ollama:
        condition: service_healthy

networks:
  ollama-network:
    driver: bridge
